spring:
    data:
        mongodb:
#            host: mongo1, mongo2
#            port: 27017, 207018
#            database: react-teste
#            username: user
#            password: password
            uri: mongodb://user:password@mongo1:27017,mongo2:27018/react-teste

