spring:
    data:
        mongodb:
#            host: localhost
#            port: 27017
#            username: user
#            password: password
            uri: mongodb://user:password@localhost:27017/react-teste

